### PR TITLE
Show total orders for customer in customers list

### PR DESCRIPTION
**Pull request by FreekPaans**
The problem is that you cannot query for totals until you know the customer ids you want to show, so you need to fetch those from the registry first, and then have other services compose their data into the page.

Is this PR a good solution?

Currently I have a couple of issues with it myself:
- The `customersController` now needs to execute 2 queries. It does both of them via the `backendCompositionService`, but I might as well do the first one directly since no other service can (and should) probably provide the list of customers.
- This solution doesn't particularly scale well: what if I need to compose in more data based on the results from `customers-list-details`. Making the `customersController` aware of this all creates coupling, thereby bypassing the value of `backendCompositionService`. I think Udi talks about raising events that a particular piece of data is available, and other services can subscribe to this and do their work. I might try to cook something like that up later.

Interested in your thoughts!

### CODE REVIEW

**Comment by mauroservienti** [comment]
Hey @FreekPaans first of all sorry for the long delay, vacation and a lot of work.

The problem you are highlighting is an obvious problem the arises immediately if you try to apply the technique illustrated in the sample to something `real-world` and it is really similar to the `select N+1` issue.

Back to your questions, before diving into to what I have in mind:

> The `customersController` now needs to execute 2 queries. It does both of them via the `backendCompositionService`, but I might as well do the first one directly since no other service can (and should) probably provide the list of customers.

That's a good point, I agree with the statement `I might as well do the first one directly since no other service can`, I decided originally to go through the `backendCompositionService` to achieve to goals:
1. Use the same API everywhere to issue queries from the client to the back-end(s)
2. Hide the complexity of the client side model composition allowing the composition strategy to change over time or to be transparently adapted to multiple different scenarios

> This solution doesn't particularly scale well: what if I need to compose in more data based on the results from `customers-list-details`. Making the `customersController` aware of this all creates coupling, thereby bypassing the value of `backendCompositionService`.

Good point once again, the solution as-is does not scale, if you need to list 10 products you are going to issue 1 request to retrieve the 10 ids and then 10 queries to retrieve descriptions, and 10 to get prices...and more..and more... `select N+1`.

> I think Udi talks about raising events that a particular piece of data is available, and other services can subscribe to this and do their work. I might try to cook something like that up later.

Events can be the `a` solution but in my opinion solve a different problem (We are actually discussing various approaches internally, stay tuned :smile:). The real solution is to batch requests and the `backendCompositionService` can do that:
- the client wants the `products-list|top:10`:

```
backendCompositionService.execute( 'products-list', 'top:10' )
    .then( function( composedResults ){
      //bind the results or do something interesting :-)
    } );
```

Now as you highlighted there just one single service that can answer the above question the `productsService`, all the others actors are simple servants that need the list of ids in order to answer the question.
- Can we say then that given a `logical client query` (the `products-list` in the above sample sample) in order to solve the request we need?
  - a query `owner`
  - zero or more query `handlers` that may integrate owner results

If we agree on the above then we can say that composing some data is at least a 2 steps process:
1. get master data (at minimum the ids)
2. get the all the others :smile: 

The above 2 steps process can be all solved by the `backendCompositionService` as in the above sample or as you highlighted can be solved using 2 explicit steps:

```
productsService.listProducts( 'top:10' )
   .then( function( productIds ) {

      backendCompositionService.compose( 'products-list', productIds )
       .then( function( composedResults ){
         //bind the results or do something interesting :-)
       } );

   } )
```

I do prefer the first approach, but it is just a technical detail.

Imagine now that the composed data that we need to show are framed as:

```
product-id (from the productsService)
      product-highlights (from the marketingService)
      product-price (from the pricingService or salesServices)
```

Using the above technique the problem is solved, or should be, if the composed `ViewModel` has data coming from 5 different services you end up with 6 requests.

There is still 1 potential issue that we need to face, now...the above starts from one assumption: there will be a `templating` engine that will passively accept the composed data and simply bind them to visualize something on the user screen.

But it is not always the case. Events to the rescue.
I imagine the following information flow
- the user clicks on a link in order to visualize a list of products (top 10)
- the actual screen transitions to the products-list-view
- the products-list-controller will query its own `productsService`
- the products-list-controller will raise a client event broadcasting `products-list-ready` along with the retrieved ids
- anyone interested in that event will chime in and issue its own queries
- at this point all the required data have been retrieved but are not in a composite structure that is not needed anymore

This second approach is more UI driven since is the `shape` of the UI that is causing someone to react to the event where on the contrary the first one is more data driven since the UI is generated by what is found in the composite structure.

In all the cases what we want to avoid is to start binding data and let the binding engine trigger the data fetch process, all the data must be fetched before binding anything to the UI other wise the `select N+1` problem will screw everything up. Imagine a scenario where:
- the list of ids is retrieved
- the list of ids is bound to the UI causing (in the above sample) 10 elements to be generated
- 10 views with 10 controllers will start fetchting data from the services

In such a scenario the only solution is to be able to batch request, the issue is that since you have no control on who is involved the only viable approach (and if you can come up with something better I'd love to hear from you) is batch based on time, you can then collect outgoing HTTP requests and issue them batched if for a certain amount of time there is no other requests (or similar logic). Somewhat fragile IMO.

Comments? Thoughts?

**Comment by mauroservienti** [comment]
```
productsService.listProducts( 'top:10' )
   .then( function( productIds ) {

      backendCompositionService.compose( 'products-list', productIds )
       .then( function( composedResults ){
         //bind the results or do something interesting :-)
       } );

   } )
```

The above comes with an interesting advantage: it removes entirely the need to define a query `owner` since all what the `backendCompositionService` is doing will be done using what I defined as `servants` so the order in which they are executed is not relevant.
Removing the `owner`, although, removes the option to have multiple levels of details:
- product
  - description
  - price
  - related-products [list]
    - description
    - price

**Comment by FreekPaans** [comment]
Wow, a lot of answers, thanks.

> Good point once again, the solution as-is does not scale, if you need to list 10 products you are going to issue 1 request to retrieve the 10 ids and then 10 queries to retrieve descriptions, and 10 to get prices...and more..and more... select N+1.

I was initially concerned with two kinds of scaling: performance and coupling. The performance problem is indeed select N+1, I solved that in my PR by indeed fetching the totals for all Id's at once (and not issue a request per Id). I think if you keep that strategy, you're gonna need at most 1 query per service.

A larger problem is that my current solution can't handle the case where you need to 'join' in additional (multi-level) data based on a 'servant' result, such as your later example with the related products, without letting the `customersController` know about the other services, which is what you want to avoid.

What I'm afraid is going to happen is that you need to define all kinds of thing such as `product-list-ids-ready`, `product-list-descriptions-ready`, `product-list-related-ready`, etc. That probably gets messy pretty fast, and you're probably introducing some hidden coupling/rigidity. Don't really see how to solve that, yet.

I'm not exactly sure in what way your flow with the `backendCompositionService` differs from the event flow: they both seem to raise events (`product-list` and `product-list-ready` respectively). Is it because you're composing the returned data into a common object? I'm not sure if that makes a fundamental difference (you could choose to not put anything in the `composedResults` and directly update views from the query handler).

> This second approach is more UI driven since is the shape of the UI that is causing someone to react to the event where on the contrary the first one is more data driven since the UI is generated by what is found in the composite structure.

I'm not sure what you mean by `shape` in here, and how that relates to being UI or data-driven, could you elaborate?

> In such a scenario the only solution is to be able to batch request, the issue is that since you have no control on who is involved the only viable approach

That makes sense, I think. 

> Somewhat fragile IMO.

Feels a bit fragile indeed (although JS' single-threadedness probably helps). As long as everything is synchronous (except the requests themselves), you can probably capture every outgoing request from a given query handler, and use that to batch stuff.

I think my biggest concern ATM is how handle multi-level data, without compromising decoupling or introducing a lot of events/query-results-notifications that are very specific to a given initial query.

I'm gonna think about it a bit more :)

**Comment by mauroservienti** [comment]
it's been a long time 😄 The work on ViewModel Composition continues and it's now tracked in a few different places:

- [ViewModel Composition](https://milestone.topics.it/categories/view-model-composition) series on my blog with man articles detailing all the aspects.
- Talks on the subject demos:
   - [Designing a UI for Microservices](https://github.com/mauroservienti/designing-a-ui-for-microservices-demos)
   - [All our Aggregates are Wrong](https://github.com/mauroservienti/all-our-aggregates-are-wrong-demos)
- [ServiceComposer](https://github.com/ServiceComposer/) an implementation of a ViewModel Composition API Gateway. Used in the aforementioned demos.

Take a look at articles about composing lists, I guess they'll answer your concerns @FreekPaans:

- [Into the darkness of ViewModels Lists Composition](https://milestone.topics.it/view-model-composition/2019/02/28/into-the-darkness-of-viewmodel-lists-composition.html)
- [The ViewModels Lists Composition Dance](https://milestone.topics.it/view-model-composition/2019/03/21/the-viewmodels-lists-composition-dance.html)

I'm closing this PR, as the repo is meant to be frozen due to the fact that it's only meant to demo the concepts expressed in [The secret of better UI composition](http://particular.net/blog/secret-of-better-ui-composition) blog post. Feel free to get in touch to further discuss by raising issues or by using the [contact form](https://mauroservienti.typeform.com/to/luuJPw) on my blog.

**Pull request closed without merging**
